version: '3'

services:
  drapo:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    user: root
    volumes:
      - ./src/web:/drapo:z
    ports:
      - "80:8000"
volumes:
  vol:
